# Client_id = P0Ue3gaYHXyDHxfkshI5SldjMZg1p8G2cyNAADQP
# Client_secret =
# In6uN7fDHGXgNMkf47zeEtDUtYLp5XCWpNPG86AdOyTlpGUIirBPA4kR9gaZADRjBPIRnOG1nRXkPKZBs75A1vKurtPWNUuUieaYqKRcYt0woiFCNgzFujSLtmAzcnlz

CLOUDINARY_URL = 'https://res.cloudinary.com/dv3tcutko/'
ROLE_ADMIN = 'ROLE_ADMIN'
ROLE_USER = 'ROLE_USER'
ROLE_SHOP = 'ROLE_SHOP'

STATUS_DOING = 'DOING'
STATUS_DELIVERING = 'DELIVERING'
STATUS_DONE = 'DONE'
