# Generated by Django 5.0 on 2023-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_sell_from_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_sell_to_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mymenuproduct',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
