# Generated by Django 5.0 on 2024-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_user_address_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='map_location',
            field=models.TextField(default='df'),
            preserve_default=False,
        ),
    ]
