# Generated by Django 5.0 on 2024-02-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.BooleanField(default=True),
        ),
    ]
