# Generated by Django 5.0 on 2024-02-19 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='point',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
