# Generated by Django 5.0 on 2024-02-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_rating_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorderproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.order'),
        ),
    ]
